# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1201bf8f8a006dc1e2e4bb9880774412a5dd5d244677ba830bf924984c97cf8b14da2cd83565b5b3368541ac793ee8dd9e48582679d20aefd8f09715ae9415e

test:
  secret_key_base: c3f9ab485427108c4d1a21612bab98e023304611fe23a17bd6b144e79e614cd808dbf9c9b0eeb7588b8e2155db4b10fd7838a0b543fbb6f076b15426fe277c87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
